SalesForceAssignment/Assignment_9/src/objects/Class__c.object
<CustomObject>
    <fields>
        <fullName>MaxSize__c</fullName>
        <label>MaxSize</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MyCount__c</fullName>
        <label>MyCount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce Assignment/Assignment_1/src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <label>LastName</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SalesForceAssignment/Assignment_13/src/classes/StudentListTest.cls
@isTest
public class StudentListTest {
    
    @testSetup static void addClass(){
        Class__c testClass = new Class__c(Name__c = 'tenth',MaxSize__c=40,MyCount__c=0);
        insert testClass;
        List<Student__c> listStud=new List<Student__c>();
        Student__c std = new Student__c(Name = 'abc' , LastName__c = 'aaa', Class__c = testClass.Id);
        listStud.add(std);
        Student__c std1 = new Student__c(Name = 'abc1' , LastName__c = 'aaa', Class__c = testClass.Id);
        listStud.add(std1);
        insert listStud;
    }
    
    @isTest static void testStudentsList() {
        Class__c test = [Select Id From Class__c  where  Name__c = 'tenth'];
        List<String> testList =  StudentList.StudentsList(test.Id);
        System.assertEquals(2, testList.size());
    }
    
    @isTest static void testgetMapOfClass() {
        System.assertEquals(1,  StudentList.getMapOfClass().size());
    }
    
    @isTest static void testgetWorkingDays() {
        Date date1=Date.newInstance(2016, 1, 6);
        Date date2=Date.newInstance(2016, 1, 8);
        System.assertEquals(3,StudentList.getWorkingDays(date1, date2));
    }
    
}